name: CI

on: [push, pull_request]

jobs:

  build:
    name: Create artifacts
    runs-on: ubuntu-latest

    steps:
      # Initialization
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install
      - name: Copy configuration
        run: cp config.json.example config.json

      # Create Chrome artifacts
      - name: Create Chrome artifacts
        run: npm run build:chrome
      - uses: actions/upload-artifact@v1
        with:
          name: ChromeExtension
          path: dist

      # Create Firefox artifacts
      - name: Create Firefox artifacts
        run: npm run build:firefox
      - uses: actions/upload-artifact@v1
        with:
          name: FirefoxExtension
          path: dist

