name: update oss attributions
on:
  push:
    branches:
      - master
    paths:
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  update-oss:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install and generate attribution
        run: |
          npm ci
          npm i -g oss-attribution-generator
          generate-attribution
          mv ./oss-attribution/attribution.txt ./public/oss-attribution/attribution.txt
      - name: Prettify attributions
        run: |
          cd ci && npx ts-node prettify.ts

      - name: Create pull request to update list
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        # v4.2.3
        with:
          commit-message: Update OSS Attribution
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: ci/oss_attribution
          title: Update OSS Attribution
          body: Automated OSS Attribution update
